ALTER TABLE `contest` ADD `startDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP  AFTER `printCodes`;
ALTER TABLE `contest` ADD `endDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP  AFTER `startDate`;

